---
# This role is allow to [get] the demo-backend-creds secrets
# in the namespace where this manifest is applied
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-backend-creds-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  resourceNames: ["demo-backend-creds"]
  verbs: ["get"]

---
# This role binding allows the demo-application serviceAccount to
# read the "demo-backend-creds" secret
# in the namespace where this manifest is applied
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-demo-backend-creds
subjects:
- kind: ServiceAccount
  name: demo-sa
roleRef:
  kind: Role
  name: demo-backend-creds-reader
  apiGroup: rbac.authorization.k8s.io
